### ISSUE TITLE
 why  constructor SensitiveWords with a parameter word do nothing??

### ISSUE THREAD

**Issue by aijingsun6** [hooj0/sensitive-words-filter#1]
file:
``` https://github.com/hooj0/sensitive-words-filter/blob/master/src/main/java/com/cnblogs/hoojo/sensitivewords/business/model/SensitiveWords.java```

line:50

**Comment by hooj0** [comment]
@aijingsun6 Cool! This is a very good question. Already fixed constructor pass argument problem. thx ~!

**Comment by zh-haining** [comment]
why these algorithms don`t surport a sensitive word that contains single char . 
such as : my content is "我是中国人，别让我失望", my sensitive word is "别".

**Comment by hooj0** [comment]
> why these algorithms don`t surport a sensitive word that contains single char .
> such as : my content is "我是中国人，别让我失望", my sensitive word is "别".

Because when I designed, I did not consider setting a single character as a "word". And the words of the sensitive vocabulary provided on the Internet start with two characters.
